apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    {{- include "tekton-events-relay.annotations" . | nindent 4 }}
  labels:
    {{- include "tekton-events-relay.labels" . | nindent 4 }}
  name: {{ include "tekton-events-relay.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "tekton-events-relay.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: AlwaysAllow
