{{- if .Values.serviceAccount.create -}}
apiVersion: v1
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
kind: ServiceAccount
metadata:
  annotations:
    {{- include "tekton-events-relay.annotations" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "tekton-events-relay.labels" . | nindent 4 }}
  name: {{ include "tekton-events-relay.serviceAccountName" . }}
{{- end }}
